import Link from "next/link";
import { TERMS_LAST_UPDATED } from "@/lib/legal";

export default function TermsPage() {
  return (
    <main className="max-w-2xl mx-auto px-6 py-10 text-neutral-800 dark:text-neutral-200">
      <Link href="/" className="text-sm text-indigo-600 dark:text-indigo-400 font-semibold">&larr; Back</Link>
      <h1 className="text-2xl font-black mt-4 mb-1">Terms of Service</h1>
      <p className="text-sm text-neutral-500 mb-8">Last updated: {TERMS_LAST_UPDATED}</p>

      <div className="flex flex-col gap-6 text-[15px] leading-relaxed">
        <section>
          <h2 className="font-bold text-lg mb-2">1. What Core AI is</h2>
          <p>
            Core AI ("the App", "we", "us") is a personal health and wellness tracking
            application operated by Linear Ventures. It helps you log food, workouts, weight,
            and other personal health data, and offers an AI assistant and AI-powered wellness
            scans (skin, eye, hair analysis) to help you understand that data.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-lg mb-2">2. Not medical advice</h2>
          <p>
            <strong>Core AI does not provide medical advice, diagnosis, or treatment.</strong>{" "}
            All AI-generated content — including wellness scan scores, observations,
            ingredient recommendations, and chat responses — is generated automatically by
            third-party AI models and is provided for general informational purposes only. It
            is not a substitute for professional medical, dermatological, or health advice.
            Always consult a qualified healthcare provider before making decisions about your
            health, diet, exercise, skincare, or any medical condition. Do not disregard or
            delay seeking professional medical advice because of something you read or were
            told in this App.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-lg mb-2">3. AI-generated content</h2>
          <p>
            Some content in the App — including nutrition estimates, workout suggestions, and
            wellness scan results — is generated by artificial intelligence (including Google's
            Gemini models) and may be inaccurate, incomplete, or occasionally wrong. You are
            responsible for using your own judgment before relying on any AI-generated output.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-lg mb-2">4. Eligibility</h2>
          <p>
            You must be at least 16 years old to create an account. If you are under 18, you
            should have a parent or guardian's permission to use the App.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-lg mb-2">5. Your account</h2>
          <p>
            You're responsible for keeping your login credentials secure and for all activity
            under your account. Let us know immediately if you suspect unauthorized access.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-lg mb-2">6. Acceptable use</h2>
          <p>
            Don't use the App to upload content you don't have the right to share, impersonate
            others, attempt to break or abuse the service, or use it for anything unlawful. We
            may suspend or terminate accounts that violate this.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-lg mb-2">7. Your data</h2>
          <p>
            See our <Link href="/privacy" className="text-indigo-600 dark:text-indigo-400 font-semibold">Privacy Policy</Link> for
            details on what we collect and how it's used. You can request deletion of your
            account and data at any time via Settings.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-lg mb-2">8. No warranty, limitation of liability</h2>
          <p>
            The App is provided "as is" without warranties of any kind, express or implied. To
            the fullest extent permitted by law, Linear Ventures is not liable for any indirect,
            incidental, or consequential damages arising from your use of the App, including
            decisions made based on AI-generated content. Your use of the App and any reliance
            on its content is at your own risk.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-lg mb-2">9. Changes</h2>
          <p>
            We may update these Terms as the App evolves. If changes are material, you'll be
            asked to review and accept the updated Terms the next time you sign in.
          </p>
        </section>

        <section>
          <h2 className="font-bold text-lg mb-2">10. Contact</h2>
          <p>
            Questions about these Terms? Reach us at{" "}
            <a href="mailto:support@linearventures.in" className="text-indigo-600 dark:text-indigo-400 font-semibold">
              support@linearventures.in
            </a>.
          </p>
        </section>
      </div>
    </main>
  );
}
