-- 0040_semantic_recall.sql — FIX 1 (semantic recall): pgvector-backed hybrid
-- search over the wellness journal, alongside the existing FTS, so a query
-- for "stressed" can match an entry that said "overwhelmed" — pure keyword
-- FTS only matches literal words.

create extension if not exists vector;

alter table wellness_journal add column embedding vector(768);

-- No ivfflat index — table sizes here are per-user hundreds/low-thousands of
-- rows at most, a sequential cosine-distance scan is fine at this scale and
-- avoids ivfflat's lists-tuning/cold-start footguns for a table this small.

-- Hybrid search: union of FTS top-K (existing search_journal logic) and
-- embedding cosine-similarity top-K, deduped, returned newest-first with a
-- similarity score for cache/debugging. query_embedding is generated by the
-- caller (lib/gemini.ts generateEmbedding) and passed in — Postgres has no
-- access to call Gemini itself.
create or replace function search_journal_hybrid(q text, query_embedding vector(768), match_count int default 8)
returns table (
  id bigint, entry_text text, entry_at timestamptz, category text, tags text[], similarity double precision
)
language sql stable security invoker as $$
  with fts as (
    select id, ts_rank(search_tsv, websearch_to_tsquery('english', q)) as rank
    from wellness_journal
    where user_id = auth.uid() and search_tsv @@ websearch_to_tsquery('english', q)
    order by rank desc
    limit match_count
  ),
  vect as (
    select id, 1 - (embedding <=> query_embedding) as similarity
    from wellness_journal
    where user_id = auth.uid() and embedding is not null
    order by embedding <=> query_embedding
    limit match_count
  ),
  combined as (
    select id from fts
    union
    select id from vect
  )
  select wj.id, wj.entry_text, wj.entry_at, wj.category, wj.tags,
    coalesce((select v.similarity from vect v where v.id = wj.id), 0) as similarity
  from wellness_journal wj
  join combined c on c.id = wj.id
  order by wj.entry_at desc
  limit match_count * 2;
$$;
